name: SpendWise CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: spendwise
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d spendwise"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/spendwise
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Install postgresql client and wait for Postgres
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client
          timeout 120 bash -c 'until pg_isready -h localhost -p 5432 -U postgres -d spendwise; do
            echo "Waiting for Postgres..."
            sleep 4
          done'

      - name: Build backend with Maven
        working-directory: ./SpendWise
        run: mvn -B clean verify

  frontend:
    needs: backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: ./spend-wise
        run: npm install

      - name: Build frontend
        working-directory: ./spend-wise
        env:
          VITE_API_BASE_URL: http://localhost:9090
        run: npm run build

      - name: Run frontend tests
        working-directory: ./spend-wise
        env:
          VITE_API_BASE_URL: http://localhost:9090
        run: npm test -- --watchAll=false

